"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-28

Hand-written rather than autogenerated: autogenerate needs a live database to diff
against, and it does not emit ``CREATE EXTENSION vector`` — which has to be the first
operation or every vector column fails.

**The dimension is hard-coded to 1024, not read from settings.** A migration is a
historical record of what the database was actually changed to. If it read
``settings.embedding_dim``, then changing EMBEDDING_DIM in .env would silently rewrite
history: this file would claim to have created vector(512) columns on a database that
has vector(1024) ones, and ``downgrade`` then ``upgrade`` would produce a schema that
no longer matches the stored embeddings. Changing the dimension is a NEW migration plus
a re-embed, deliberately.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

EMBEDDING_DIM = 1024

VERTICALS_SQL = "'insurance', 'real_estate'"
ENRICH_VERTICALS_SQL = "'insurance', 'real_estate', 'neither'"


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "raw_posts",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("source", sa.String(32), nullable=False),
        sa.Column("external_id", sa.String(64), nullable=False),
        sa.Column("parent_external_id", sa.String(64), nullable=True),
        sa.Column("subsource", sa.String(128), nullable=True),
        sa.Column("vertical_hint", sa.String(32), nullable=True),
        sa.Column("url", sa.Text, nullable=False),
        sa.Column("author", sa.String(128), nullable=True),
        sa.Column("title", sa.Text, nullable=True),
        sa.Column("body", sa.Text, nullable=False),
        sa.Column("score", sa.Integer, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "filter_state", sa.String(16), nullable=False, server_default="pending"
        ),
        sa.Column("filter_reason", sa.String(64), nullable=True),
        sa.UniqueConstraint(
            "source", "external_id", name="uq_raw_posts_source_external"
        ),
        sa.CheckConstraint(
            "filter_state IN ('pending', 'passed', 'rejected')",
            name="ck_raw_posts_filter_state",
        ),
        sa.CheckConstraint(
            f"vertical_hint IS NULL OR vertical_hint IN ({VERTICALS_SQL})",
            name="ck_raw_posts_vertical_hint",
        ),
    )
    op.create_index(
        "ix_raw_posts_passed",
        "raw_posts",
        ["filter_state"],
        postgresql_where=sa.text("filter_state = 'passed'"),
    )
    op.create_index(
        "ix_raw_posts_created_at", "raw_posts", [sa.text("created_at DESC")]
    )

    op.create_table(
        "clusters",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("vertical", sa.String(32), nullable=False),
        sa.Column("label", sa.Text, nullable=False),
        sa.Column("centroid", Vector(EMBEDDING_DIM), nullable=False),
        sa.Column("member_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("distinct_authors", sa.Integer, nullable=False, server_default="0"),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("score", sa.Float, nullable=True),
        sa.Column("scored_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            f"vertical IN ({VERTICALS_SQL})", name="ck_clusters_vertical"
        ),
        # INV-7 as a write-time constraint: a clustering bug fails at INSERT instead of
        # surfacing weeks later as a wrong digest ranking.
        sa.CheckConstraint(
            "distinct_authors <= member_count",
            name="ck_clusters_authors_lte_members",
        ),
    )
    op.create_index(
        "ix_clusters_vertical_score",
        "clusters",
        ["vertical", sa.text("score DESC NULLS LAST")],
    )

    op.create_table(
        "enriched_signals",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column(
            "raw_post_id",
            sa.BigInteger,
            sa.ForeignKey("raw_posts.id"),
            nullable=False,
            unique=True,
        ),
        sa.Column("vertical", sa.String(32), nullable=False),
        sa.Column("pain_point", sa.Text, nullable=False),
        sa.Column("who_has_it", sa.Text, nullable=False),
        sa.Column("current_workaround", sa.Text, nullable=True),
        sa.Column("willingness_to_pay_signal", sa.String(16), nullable=False),
        sa.Column("buildable_with_llm", sa.Boolean, nullable=False),
        sa.Column("relevance", sa.SmallInteger, nullable=False),
        sa.Column("model", sa.String(64), nullable=False),
        sa.Column(
            "enriched_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=True),
        sa.Column(
            "cluster_id", sa.BigInteger, sa.ForeignKey("clusters.id"), nullable=True
        ),
        sa.CheckConstraint(
            f"vertical IN ({ENRICH_VERTICALS_SQL})", name="ck_signals_vertical"
        ),
        sa.CheckConstraint(
            "willingness_to_pay_signal IN ('none', 'implied', 'explicit')",
            name="ck_signals_wtp",
        ),
        sa.CheckConstraint("relevance BETWEEN 0 AND 10", name="ck_signals_relevance"),
        sa.CheckConstraint(
            "vertical <> 'neither' OR relevance = 0", name="ck_signals_neither_zero"
        ),
    )
    op.create_index("ix_signals_cluster", "enriched_signals", ["cluster_id"])
    op.create_index(
        "ix_signals_vertical_relevance",
        "enriched_signals",
        ["vertical", sa.text("relevance DESC")],
    )

    op.create_table(
        "enrichment_batches",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("batch_id", sa.String(128), nullable=False, unique=True),
        sa.Column("status", sa.String(16), nullable=False, server_default="pending"),
        sa.Column("request_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'collected', 'failed')",
            name="ck_enrichment_batches_status",
        ),
    )
    op.create_index("ix_enrichment_batches_pending", "enrichment_batches", ["status"])

    op.create_table(
        "digests",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cluster_ids", sa.ARRAY(sa.BigInteger), nullable=False),
        sa.Column("markdown", sa.Text, nullable=False),
        sa.Column(
            "delivered", sa.Boolean, nullable=False, server_default=sa.text("false")
        ),
    )


def downgrade() -> None:
    op.drop_table("digests")
    op.drop_table("enrichment_batches")
    op.drop_table("enriched_signals")
    op.drop_table("clusters")
    op.drop_table("raw_posts")
    # The extension is intentionally NOT dropped. Other databases on the same cluster
    # may depend on it, and `alembic downgrade base` should undo this schema, not
    # uninstall a server-wide extension.
